---

- name: Remove nftables package
  apt:
    name: '{{ firewall_packages }}'
    state: absent
    purge: true
    autoremove: true

- name: Remove nftables directory
  file:
    path: /etc/nftables
    state: absent

- name: Remove the system log configuration
  register: rsyslog_config
  file:
    path: /etc/rsyslog.d/nftables.conf
    state: absent

- name: Restart rsyslog now
  when: rsyslog_config.changed
  systemd:
    name: rsyslog
    state: restarted

- name: Remove the logrotate configutation
  file:
    path: /etc/logrotate.d/nftables
    state: absent
