---

# The following tasks are run when the system is remote (e.g. cloud server)
- name: Store the remote IP address (IPv4)
  set_fact:
    remote_ip: '{{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] | default(None) }}'

- name: Store the remote IP address (IPv6)
  when: remote_ip | length == 0
  set_fact:
    remote_ip: '{{ hostvars[inventory_hostname]["ansible_default_ipv6"]["address"] | default(None) }}'

- name: Check the type of IP address for the remote host
  set_fact:
    remote_ip_private: '{{ (remote_ip | ipaddr("private")) != None }}'
