---

- name: Create the nftables directory
  file:
    path: /etc/nftables
    state: directory

- name: Copy the main rules files
  notify: Restart nftables
  template:
    src: rules/{{ file.name }}.nft
    dest: /etc/nftables/{{ file.name }}.nft
    mode: 0600
  loop: '{{ rule_files | selectattr("include", "equalto", true) | list }}'
  loop_control:
    loop_var: file

- name: Remove the excluded files
  notify: Restart nftables
  file:
    path: /etc/nftables/{{ file.name }}.nft
    state: absent
  loop: '{{ rule_files | selectattr("include", "equalto", false) | list }}'
  loop_control:
    loop_var: file

- name: Copy the nftables parent configuration file
  notify: Restart nftables
  template:
    src: rules/main.nft
    dest: /etc/nftables.conf
    mode: '0600'
